### ISSUE TITLE
Crash with the mod Aquaculture 2

### ISSUE THREAD

**Issue by Zannnol** [pitbox46/FishingOverhaul#3]
I was doing a little modpack to play with my friends and we tried to get the mod Aquaculture and Fishing Overhaul together with some other simple mods.
Unfortunately when a fish takes the bait the game just crash.

Mods version :
- Aquaculture 2.4.8 for Forge 1.19.2
- Fishing Overhaul 1.0.0 for Forge 1.19.2

Here are the crashlogs
[crash-2022-11-22_21.23.03-server.txt](https://github.com/pitbox46/FishingOverhaul/files/10070902/crash-2022-11-22_21.23.03-server.txt)

**Comment by pitbox46** [comment]
Apologies for never getting to this. This is an issue because Fishing Overhaul wasn't actually supported for 1.19.2. It was only really supported for 1.19, and then I got too busy to update it for later versions
